version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./reactapp
      dockerfile: ./react.Dockerfile
    volumes:
      - './reactapp:/app'
      - '/react/node_modules'
    ports:
      - 3000:3000
    depends_on:
      - python
    stdin_open: true
    command: npm start
  
  python:
    depends_on:
      - db
    network_mode: "service:db"
    container_name: python
    restart: unless-stopped
    stdin_open: true
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=server.py
      - DEV_DATABASE_URL=postgresql://root:secret@localhost:5432/delivery
  
  beat:
    build: .
    container_name: 'celery-beat'
    command: celery -A app.celery beat -s ./celerybeat-schedule  
    network_mode: "service:db"
    depends_on:
      - redis
    environment:
      - FLASK_APP=server.py
      - DEV_DATABASE_URL=postgresql://root:secret@localhost:5432/delivery
  
  worker:
    build: .
    container_name: 'celery-worker'
    command: celery -A app.celery worker --loglevel=info
    network_mode: "service:db"
    depends_on:
      - redis
    environment:
      - FLASK_APP=server.py
      - DEV_DATABASE_URL=postgresql://root:secret@localhost:5432/delivery

  db:
    container_name: db
    build:
      context: ./app/database
      dockerfile: ./db.Dockerfile
    environment:
      POSTGRES_DB: "delivery"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
      - "5000:5000"

  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - 6379:6379
    links:
      - db