version: "3"

services:    
  python:
    depends_on:
      - db
    network_mode: "service:db"
    image: python:3.10.5
    container_name: python
    restart: unless-stopped
    stdin_open: true
    build: .
    command: python3 google_api.py
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "delivery"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
volumes:
  my-db:
    driver: local